# ============= SCOPE CONTEXT 0
SCPCNX_NONE = 0
SCPCNX_FUNC = 1
#---- CONTROL FLOW
SCPCNX_IF = 2
SCPCNX_ELSE = 3
SCPCNX_WHILE = 4
SCPCNX_FOR = 5
SCPCNX_MATCH = 6
SCPCNX_CASE = 7
#------ OTHERS
SCPCNX_EVAL = 8
SCPCNX_MAP = 9


# ======================== LINE CONTEXT
# DEF 0
LNCNX_DEFVAR = 0
LNCNX_DEFFUNC = 1
LNCNX_DEFMAP = 2
LNCNX_DEFIMPRT = 3
# CONTROL FLOW 1
LNCNX_IF = 10
LNCNX_ELSE = 11
LNCNX_WHILE = 12
LNCNX_FOR = 13
LNCNX_MATCH = 14
LNCNX_CASE = 15
# OTHERS 2
LNCNX_PIPE = 20
LNCNX_TYPECHECK = 21
LNCNX_MAP = 22
