#================ 0 DIRECTIVES
DIR_IMPORT = 0
DIR_APPEND = 1
DIR_PERMISSION = 2

#================ 1 DECLARATIVES
DEC_FUNC = 10

#================ 2 TYPES
TYP_INT = 20
TYP_FLOAT = 21
TYP_BOOL = 22
TYP_STR = 23
TYP_ARRY = 24

#================ 3 TYPE MODIFIERS
TYM_MUT = 30
TYM_IMM = 31
TYM_PUB = 32

#================ 4 CONTROL FLOW
CTF_IF = 40
CTF_THEN = 41
CTF_ELSE = 42
CTF_IFELSE = 43
CTF_WHILE = 44
CTF_FOR = 45
CTF_DO = 46
CTF_UNTIL = 47
CTF_REPEAT = 48

#================= 5 ARITHMATIC OPERATORS
ARO_PLUS = 50
ARO_MINUS = 51
ARO_MULTI = 52
ARO_DIV = 53
ARO_POWER = 54
ARO_PERCENT = 55

#================ 6 LOGIC OPERATORS
LOG_AND = 60
LOG_OR = 61
LOG_NOT = 62
LOG_TRUE = 63
LOG_FALSE = 64

#================= 7 COMPARSON OPERATORS
COM_EQUAL = 70
COM_NEQUAL = 71
COM_LESSTHAN = 72
COM_GREATERTHAN = 73

#================= 8 SYMBOLS PAIRS
SYM_LBRAKET = 80
SYM_RBRAKET = 81
SYM_LCBRAKET = 82
SYM_RCBRAKET = 83
SYM_LPARANTH = 84
SYM_RPARANTH = 85
SYM_LARRO = 86
SYM_RARRO = 87
SYM_QOUTES = 88
SYM_DQOUTES = 98
#================= 9 SYMBOLS SINGLE
SYM_HASH = 90
SYM_AT = 91
SYM_DOLLAR = 92
SYM_COMMA = 93
SYM_DOT = 94
SYM_COLON = 95
SYM_BACKLASH = 96
SYM_FORWARDLASH = 97
SYM_QUESTION = 98
SYM_EXLAM = 99
